# Generated by Django 4.1.1 on 2022-10-08 18:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='breed',
            field=models.CharField(max_length=20, verbose_name='Breed'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='coatcolor',
            field=models.CharField(max_length=15, verbose_name='Coat Color'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='notes',
            field=models.TextField(max_length=250, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='owneraddress',
            field=models.CharField(max_length=100, verbose_name='Owner Address'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='ownername',
            field=models.CharField(max_length=20, verbose_name='Owner Name'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='ownerphone',
            field=models.CharField(max_length=12, verbose_name='Owner Phone'),
        )
    ]
